version: '3.8'

services:
  # Service de production (build optimisé)
  app-prod:
    build: .
    container_name: job-search-prod
    ports:
      # On mappe le port externe au port interne défini par SERVER_PORT
      # Ces ports seront remplacés par les valeurs des fichiers .env
      - "${SERVER_PORT:-4059}:${SERVER_PORT:-4059}"
    env_file:
      # Charger d'abord le fichier .env à la racine
      - ./.env
      # Puis charger le fichier server/.env (prioritaire)
      - ./server/.env
    environment:
      - NODE_ENV=production
    # Ajout d'un healthcheck pour vérifier que le serveur fonctionne correctement
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${SERVER_PORT:-4059}/api/auth"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
