version: '3.8'

services:
  # Service de production
  app-prod:
    build: .
    container_name: job-search-prod
    restart: unless-stopped
    ports:
      # Ports fixes pour la production
      - "4059:4059"  # Backend API
      - "4060:4060"  # Frontend
    environment:
      - NODE_ENV=production
      - SERVER_PORT=4059
      - REACT_APP_PORT=4060
      - REACT_APP_FRONTEND_URL=http://localhost:4060
      - REACT_APP_API_URL=http://localhost:4059/api
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4059/api/auth"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
