version: '3.8'

services:
  # Service backend (serveur Node.js)
  backend:
    build: .
    container_name: job-search-backend
    restart: unless-stopped
    ports:
      # Backend API
      - "4059:4059"
    environment:
      - NODE_ENV=production
      - SERVER_PORT=4059
      - REACT_APP_PORT=4060
      - REACT_APP_FRONTEND_URL=http://localhost:4060
      - REACT_APP_API_URL=http://localhost:4059/api
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4059/api/auth"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./build:/app/build  # Partage le dossier build pour Nginx
  
  # Service frontend (serveur Nginx)
  frontend:
    image: nginx:alpine
    container_name: job-search-frontend
    restart: unless-stopped
    ports:
      # Frontend
      - "4060:4060"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/app/build  # Montage des fichiers statiques
    depends_on:
      - backend
