services:
  # Service backend (serveur Node.js)
  backend:
    build: .
    container_name: job-search-backend
    restart: unless-stopped
    env_file:
      - ./.env.production
      - ./server/.env
    expose:
      - "4059"  # Exposé au réseau interne uniquement
    volumes:
      - ./build:/app/build  # Partage le dossier build
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4059/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.jobs.creachtheo.fr`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=4059"
  
  # Service frontend (serveur Nginx)
  frontend:
    image: nginx:alpine
    container_name: job-search-frontend
    restart: unless-stopped
    expose:
      - "4060"  # Exposé au réseau interne uniquement
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/app/build  # Montage des fichiers statiques
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`jobs.creachtheo.fr`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=4060"

  # Service Traefik pour gérer les certificats SSL et le routage
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=creach.t@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Redirection HTTP vers HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt

volumes:
  traefik-certificates:
