
services:
  # Service de production (build optimisé)
  app-prod:
    build: .
    container_name: job-search-prod
    ports:
      - "4060:4060"
      - "4059:4059"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production